sudo: false
language: cpp

compiler:
  - clang++
  - g++
  - g++4.8
addons:
  apt:
    packages:
    - liblua5.2-dev
    - libboost-all-dev
    - g++4.8
env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug
script:
  - mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && make && ./test_runner
