sudo: false
language: cpp

compiler:
  - clang
  - g++
before_install:
  - pip install --user codecov
install:
  - if [ "$CXX" = "g++" ] && [ "$CXX_FLAGS" = "-std=c++11" ]; then export CXX="g++-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - liblua5.2-dev
    - libboost-all-dev
    - g++-4.8
    - cmake
env:
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++03
  - BUILD_TYPE=Debug CXX_FLAGS=-std=c++03
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++11
  - BUILD_TYPE=Debug CXX_FLAGS=-std=c++11
script:
  - mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} && make && make test
after_success:
  - cd ../ && clang++ test/test.cpp -Iinclude `pkg-config lua5.2 --libs --cflags` -coverage -o covtest && ./covtest
  - codecov
