sudo: false
language: cpp

compiler:
  - clang++
  - g++
  - g++4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - liblua5.2-dev
    - libboost-all-dev
    - gcc-4.8
    - g++-4.8
    - cmake
env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug
script:
  - mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && make && ./test_runner
