sudo: false
language: cpp

compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
    - liblua5.2-dev
    - libboost-all-dev
script:
  - mkdir build && cd build && cmake ../ && make && ./test_runner
