version: 1.0.{build}
image: Visual Studio 2015
configuration:
- Debug
- Release
environment:
  matrix:
  - CMAKE_GEN_TYPE: '"Visual Studio 14 2015"'
  - CMAKE_GEN_TYPE: '"Visual Studio 12 2013"'
  - CMAKE_GEN_TYPE: '"Visual Studio 11 2012"'
    ADDITIONAL_INCLUDE_PATH: C:\Libraries\boost
  - CMAKE_GEN_TYPE: '"Visual Studio 10 2010"'
    ADDITIONAL_INCLUDE_PATH: C:\Libraries\boost
install:
- ps: >-
    if(!(Test-Path -Path lua-5.3.2 )){
      choco install 7zip.commandline
      Invoke-WebRequest  http://www.lua.org/ftp/lua-5.3.2.tar.gz -OutFile lua-5.3.2.tar.gz
      7z x lua-5.3.2.tar.gz
      7z x lua-5.3.2.tar
    }
cache: lua-5.3.2
before_build:
- cmd: cmake ./ -G %CMAKE_GEN_TYPE% -DADDITIONAL_INCLUDE_PATH=%ADDITIONAL_INCLUDE_PATH%
build:
  project: Kaguya.sln
  verbosity: minimal
test_script:
- cmd: ctest -V
